// react-message-app/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [message, setMessage] = useState('');
  const [displayMessage, setDisplayMessage] = useState('Hello World');
  
  const updateMessage = () => {
    setDisplayMessage(message || 'Hello World');
  };

  return (
    <div style={{ textAlign: 'center', marginTop: '20px'}}>
      <h2>{displayMessage}</h2>
      <input
        type="text"
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        placeholder="Message to Display"
      />
      <button onClick={updateMessage}>Display Message</button>
    </div>
  );
}

export default App;

// todo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  message: string = '';
  displayMessage: string = 'Hello World'!

  updateMessage() {
    this.displayMessage = this.message || 'Hello World';
  }
}

<div style="text-align: center; margin-top: 20px">
  <h2>{{ displayMessage }}</h2>
  <input 
    type="text"
    [(ngModel)]="message"
    placeholder="Message to Display"
  />
  <button (click)="updateMessage()">Display Message</button>
</div>
